# Numpy Quickstart
From: [Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#quickstart-tutorial)

## Basic Numpy Array Example

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
type(a)
a='the'

str

In [9]:
a.shape

AttributeError: 'str' object has no attribute 'shape'

In [129]:
a.ndim

2

In [130]:
a.dtype.name

'int64'

In [131]:
a.itemsize

8

In [132]:
a.size

15

In [133]:
type(a)

numpy.ndarray

In [134]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [135]:
repr(type(b))

"<class 'numpy.ndarray'>"

## Array Creation

### Basic use of array function

In [136]:
a = np.array([2,3,4]) # can use python list
a.dtype

dtype('int64')

In [137]:
b = np.array((1.2,3.5,5.1)) # can use python tuple
b.dtype

dtype('float64')

In [138]:
c = np.array(4,5,6) # can't use a list of individual arguments

ValueError: only 2 non-keyword arguments accepted

### Multi-dimensional array creation

In [ ]:
# sequences of sequences become 2-D arrays
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]]) # can use list of lists
twoD

In [ ]:
twoD = np.array(((1,2,3),(4,5,6),(7,8,9))) # can use tuple of tuples
twoD

In [ ]:
twoD = np.array([(1,2,3),(4,5,6),(7,8,9)]) # can use list of tuples
twoD

In [ ]:
twoD = np.array(([1,2,3],[4,5,6],[7,8,9])) # can use tuple of lists
twoD

In [ ]:
# can explicitly set the type of the argument
twoD = np.array([(1,2),(3,4)], dtype=complex)
twoD

### Special / Placeholder array creation

In [ ]:
np.zeros((3,4))

In [ ]:
np.ones((2,3,4), dtype=np.int16)

In [ ]:
np.empty((2,3))

### Sequential array creation

In [ ]:
np.arange(10,30,5)

In [ ]:
np.arange(10,31,5)

In [ ]:
np.arange(0,2,0.3)

In [ ]:
np.linspace(0,2,9)

In [ ]:
np.linspace(0,2,9,endpoint=False)

In [ ]:
np.linspace(0,2,9,retstep=True)

In [ ]:
import math
x = np.linspace(0, 2 * math.pi, 10)
f = np.sin(x)
f

## Basic Operations
Arithmetic operators (including *) operate on arrays apply _elementwise_, resulting in a new array. 

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [ ]:
a - b

In [ ]:
b ** 2

In [ ]:
10 * np.sin(a)

In [ ]:
a < 35

### Product operator * vs matrix product

In [ ]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A)
print(B)

In [ ]:
# * operator is _elementwise_ operation
A * B

In [ ]:
# matrix product uses @ operator
A @ B

In [ ]:
# matrix product an also be done wiht .dot() function
A.dot(B)

In [ ]:
# inplace operators (+=, *=l)
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a)
print(b)

In [ ]:
a *= 3
a

In [ ]:
b += a  # result in upcast to float
print(a.dtype, b.dtype, b)

In [ ]:
a += b  # b not automatically converted to int

In [ ]:
b += a

### Upcasting during operation
When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [145]:
a = np.ones(3, dtype=np.int32)
print(a.dtype.name)
b = np.linspace(0, math.pi, 3)
print(b.dtype.name)

int32
float64


In [144]:
c = a + b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [147]:
d = np.exp(c*1J)
print(d.dtype.name)
d

complex128


array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

### Unary operation

In [150]:
a = np.random.random((2,3))
a

array([[0.79618826, 0.56085781, 0.95846858],
       [0.95552261, 0.27690086, 0.18181967]])

In [151]:
a.sum()  # sums over all the elements of the array

3.7297577761301506

In [152]:
a.min() # operates over the entire array

0.1818196685103829

In [153]:
a.max() # operates over the entire array

0.9584685785550004

In [154]:
a.sum(axis=0)  # sums each column

array([1.75171087, 0.83775866, 1.14028825])

In [156]:
a.min(axis=1)  # operates on each row

array([0.56085781, 0.18181967])

In [157]:
a.cumsum(axis=1)  # cumulative sum along each row

array([[0.79618826, 1.35704606, 2.31551464],
       [0.95552261, 1.23242346, 1.41424313]])

### Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [158]:
B = np.arange(3)
B

array([0, 1, 2])

In [159]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [160]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [162]:
C = np.array([2., -1., 4.])
np.add(B,C)

array([2., 0., 6.])

> See also
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where